prefix=[<gold>PlayerKits</gold>]
cooldown-expires-at={0} <gray>Cooldown for kit <yellow>{1}</yellow> expires at <yellow>{2}</yellow> for player {3} </gray>
items.open-last-inventory=<red>Back</red>
inventory.not-enough-space={0} <red>Inventory from {1} has not enough space.</red>
commands.playerkit.create.success={0} <gray>The Kit <yellow>{1}</yellow> was <green>successfully</green> created.</gray>
commands.playerkit.delete.success={0} <gray>The Kit <yellow>{1}</yellow> was <green>successfully</green> deleted.</gray>
commands.playerkit.delete.failure={0} <gray>The Kit <yellow>{1}</yellow> could <red>not</red> be deleted.</gray>
commands.playerkit.setup.already-in-setup={0} <red>This Kit has already a setup!</red>
commands.playerkit.setup.help={0} <gray>Type: /playerkit setup {1}</gray>
commands.playerkit.setup.items-set={0} <green>You have set the items for the Kit {1}</green>
commands.playerkit.setup.property-set={0} <green>Kit property {1} was set to {2}</green>
commands.playerkit.setup.type-not-supported={0} <red>This type is not supported!</red>
kit.grant.success={0} <gray>The Kit <yellow>{1}</yellow> was <green>successfully</green> added to your inventory.</gray>
kit.grant.other.success={0} <gray>The Kit <yellow>{1}</yellow> was <green>successfully</green> added to {2}`s inventory.</gray>
kit.not-found={0} <red>The Kit {1} could not be found.</red>
kit.grant.special={0} Hey, {1}! Weil du ein Teil der Draconia-MC Community warst, erh\u00E4ltst du von uns ein besonderes Geschenk. Viel Spa\u00DF damit!