cooldown-expires-at=<gray>Cooldown for kit <yellow>{0}</yellow> expires at <yellow>{1}</yellow> for player {2} </gray>
items.open-last-inventory=<red>Back</red>
inventory.not-enough-space=<red>Inventory from {0} has not enough space.</red>
commands.playerkit.create.success=<gray>The Kit <yellow>{0}</yellow> was <green>successfully</green> created.</gray>
commands.playerkit.create.failure=<gray>The Kit <yellow>{0}</yellow> could <red>not</red> be created.</gray>
commands.playerkit.delete.success=<gray>The Kit <yellow>{0}</yellow> was <green>successfully</green> deleted.</gray>
commands.playerkit.delete.failure=<gray>The Kit <yellow>{0}</yellow> could <red>not</red> be deleted.</gray>
kit.grant.success=<gray>The Kit <yellow>{0}</yellow> was <green>successfully</green> added to your inventory.</gray>
kit.grant.other.success=<gray>The Kit <yellow>{0}</yellow> was <green>successfully</green> added to {1}`s inventory.</gray>
kit.not-found=<red>The Kit {0} could not be found.</red>
kit.grant.special=Hey, {0}! Weil du ein Teil der Draconia-MC Community warst, erh‰ltst du von uns ein besonderes Geschenk. Viel Spaﬂ damit!