# docker compose up -d
services:
  mariadb:
    image: mariadb
    container_name: 'player_kits_mariadb'
    ports:
      - "3306:3306"
    shm_size: 128mb
    volumes:
      - ./mariadb/data/:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: playerkits
      MARIADB_USER: playerkits
      MARIADB_PASSWORD: playerkits
      MARIADB_DATABASE: playerkits
    networks:
      - player_kits_mariadb_net

networks:
  player_kits_mariadb_net:
    driver: bridge